config/routes.rb
Rails.application.routes.draw do
  get 'purchases/create'

  get 'home/index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

 protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  protect_from_forgery prepend: true
  before_action :authenticate_user!
  def create
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/home/index.html.erb
<div class="row">
  <div class="col-sm-12 text-xs-center bootstrap-welcome">
    <h1>Welcome <%= current_user.email if user_signed_in?%></h1>
    <p><%= link_to 'edit profile', edit_user_registration_path(current_user) if user_signed_in?%></p>
    <p><%= link_to 'login', new_user_session_path() unless user_signed_in?%></p>
    <p><%= link_to 'sign_in', new_user_registration_path() unless user_signed_in?%></p>
    <p><%= link_to 'logout', destroy_user_session_path(), method: :delete if user_signed_in? %></p>
  </div>
</div>


<h1>Home#index</h1>
<p>Contratar sicario precio $50.000 <%= link_to 'Comprar',  purchases_create_path() %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AgileClass</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/purchases/create.html.erb
<h1>Purchases#create</h1>
<p>Find me in app/views/purchases/create.html.erb</p>